name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - Subtest
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - Subtest

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ cecfdb79452f681a61ac04c119ac1240c7021fc7e198099cd787ed2457c90a4a4-d15b1e6a-5f54-496f-9b6d-ccf69252ac8f00f128379 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/vp" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "/" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ cecfdb79452f681a61ac04c119ac1240c7021fc7e198099cd787ed2457c90a4a4-d15b1e6a-5f54-496f-9b6d-ccf69252ac8f00f128379 }}
          action: "close"
